### ISSUE TITLE
Sometimes some of <Ctrl-...> mappings don't work

### ISSUE THREAD

**Issue by deathmaz** [dzhou121/gonvim#35]
Hi @dzhou121, i have this in my init.vim `nnoremap <silent><C-p> :CtrlSpace<CR>`, but in gonvim when i press `<C-p>` it just moves the cursor one line upper
also i have these settings for file saving:
```viml
nmap <c-s> :wa!<CR>
imap <c-s> <Esc><c-s>
```
the first one doesn't work, the second one inserts `<C-D-S>`
next thing is that i'm using https://github.com/junegunn/fzf.vim so when i run `:Files` and press `<C-n>` or `<C-p>` to move around it inserts `;5u` inside of fzf input prompt

I'm using `NVIM v0.2.0` on `Kernel: 4.9.31-1-MANJARO x86_64 (64 bit) Desktop: Xfce 4.12.3 Distro: Manjaro Linux`

Thank you very much for your work !

EDIT: `<C-f>` and `<C-b>` in normal mode also don't work

**Comment by dzhou121** [comment]
Please re-download v0.1 release. It should be fixed.

**Comment by deathmaz** [comment]
Thank you for the fix!
 But i still have problems with this `nnoremap <silent><C-p> :CtrlSpace<CR>` and this
``` viml
nmap <c-s> :wa!<CR>
imap <c-s> <Esc><c-s>
```
the first one doesn't work, the second one inserts `<C-D-S>`

other stuff works fine

**Comment by dzhou121** [comment]
Does it work properly if you exec ```:CtrlSpace<CR>``` directly in cmdline?

**Comment by deathmaz** [comment]
Yes, it is

**Comment by dzhou121** [comment]
Which keyboard layout are you using?

**Comment by deathmaz** [comment]
QWERTY, it works fine in terminal neovim

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
`<C-s>` works in my environment.

**Comment by deathmaz** [comment]
Strange, for me it works fine in terminal, but not in gonvim

**Comment by Shougo** [comment]
```vim
function! s:getchar() abort
  redraw | echo 'Press any key: '
  let c = getchar()
  while c ==# "\<CursorHold>"
    redraw | echo 'Press any key: '
    let c = getchar()
  endwhile
  redraw | echomsg printf('Raw: "%s" | Char: "%s"', c, nr2char(c))
endfunction
command! GetChar call s:getchar()
```

Please execute :GetChar and press <C-s>.

**Comment by deathmaz** [comment]
The output is:
`Raw: "46" | Char: "."`

**Comment by deathmaz** [comment]
I have installed old version of gonvim globally, `<C-s>` and `<C-p>` work fine in it

**Comment by Shougo** [comment]
The output is:
```
Raw: "19" | Char:"^S"
```

**Comment by deathmaz** [comment]
i just tested `:GetChar` with `<C-s>`
in terminal nvim: `Raw: "19" | Char: "^S"`
in gonvim: `Raw: "~@<80>~@^D~@<80>^S" | Char: ""`
in old gonvim: `Raw: "19" | Char: "^S"`

**Comment by dzhou121** [comment]
It looks like your meta key is pressed as well. Effectively gonvim is sending <C-D-s> to nvim.

**Comment by deathmaz** [comment]
i found the problem, i always remap right Window key so it works like Ctrl, when it's not remapped everything works fine
the question is why it works in terminal and old gonvim?

**Comment by deathmaz** [comment]
Thank you guys for your help

**Comment by dzhou121** [comment]
In old gonvim, when it sees crtl modifier, it just send it without caring other modifiers. So the Window key is ignored. 

Not sure for terminal nvim though.
